# mkdocs.yml
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: python
          class: python
          validator: !!python/name:markdown_exec.validator
          format: !!python/name:markdown_exec.formatter
            # ...one fence for each language we support:
            # bash, console, md, markdown, py, python, pycon, sh, tree

